# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres:13-buster
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5435:5432
